import React, {useEffect, useState} from 'react';
import {Alert, Pressable, StyleSheet, Text, View} from 'react-native';
import {useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {RootStackParamList} from '../../navigation/types';
import {getHealth, updateHealth, listVaccinations, addVaccination, removeVaccination} from '../../api/features.api';
import {Screen} from '../../components/Screen'; import {AppInput} from '../../components/AppInput'; import {AppButton} from '../../components/AppButton';
import {getApiErrorMessage} from '../../api/client'; import {colors,radius,spacing,typography} from '../../theme';
type Props=NativeStackScreenProps<RootStackParamList,'PetHealth'>;
export function PetHealthScreen({route}:Props){const id=route.params.petId,qc=useQueryClient();const health=useQuery({queryKey:['health',id],queryFn:()=>getHealth(id)});const vaccines=useQuery({queryKey:['vaccinations',id],queryFn:()=>listVaccinations(id)});const [allergies,setAllergies]=useState('');const [meds,setMeds]=useState('');const [conditions,setConditions]=useState('');const [vet,setVet]=useState('');const [vetPhone,setVetPhone]=useState('');const [notes,setNotes]=useState('');const [vName,setVName]=useState('');const [given,setGiven]=useState('');const [due,setDue]=useState('');const [clinic,setClinic]=useState('');
useEffect(()=>{if(health.data){setAllergies(health.data.allergies||'');setMeds(health.data.medications||'');setConditions(health.data.conditions||'');setVet(health.data.vet_name||'');setVetPhone(health.data.vet_phone||'');setNotes(health.data.notes||'');}},[health.data]);
const save=useMutation({mutationFn:()=>updateHealth(id,{allergies:allergies||null,medications:meds||null,conditions:conditions||null,vet_name:vet||null,vet_phone:vetPhone||null,notes:notes||null}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['health',id]});Alert.alert('บันทึกสุขภาพแล้ว');},onError:e=>Alert.alert('บันทึกไม่สำเร็จ',getApiErrorMessage(e))});
const add=useMutation({mutationFn:()=>addVaccination(id,{name:vName.trim(),given_at:given,next_due_at:due||undefined,clinic_name:clinic||undefined}),onSuccess:()=>{setVName('');setGiven('');setDue('');setClinic('');void qc.invalidateQueries({queryKey:['vaccinations',id]});},onError:e=>Alert.alert('เพิ่มวัคซีนไม่สำเร็จ',getApiErrorMessage(e))});
return <Screen><View style={styles.hero}><Text style={styles.title}>🩺 Health Profile</Text><Text style={styles.desc}>ข้อมูลส่วนนี้เป็น Private โดยค่าเริ่มต้น ข้อมูลฉุกเฉินที่ต้องการเปิดเผยให้ตั้งค่าในหน้า Emergency Information</Text></View><AppInput label="แพ้อาหาร / ยา" value={allergies} onChangeText={setAllergies}/><AppInput label="ยาประจำ" value={meds} onChangeText={setMeds}/><AppInput label="โรคประจำตัว" value={conditions} onChangeText={setConditions}/><AppInput label="สัตวแพทย์ / คลินิกประจำ" value={vet} onChangeText={setVet}/><AppInput label="เบอร์ติดต่อคลินิก" value={vetPhone} onChangeText={setVetPhone} keyboardType="phone-pad"/><AppInput label="บันทึกสุขภาพ" value={notes} onChangeText={setNotes} multiline style={{minHeight:90,textAlignVertical:'top'}}/><AppButton title="บันทึก Health Profile" onPress={()=>save.mutate()} loading={save.isPending}/><Text style={styles.section}>วัคซีน</Text>{vaccines.data?.map(v=><View key={v.id} style={styles.card}><View style={{flex:1}}><Text style={styles.cardTitle}>{v.name}</Text><Text style={styles.meta}>ฉีด {v.given_at}{v.next_due_at?` · นัดถัดไป ${v.next_due_at}`:''}</Text>{!!v.clinic_name&&<Text style={styles.meta}>{v.clinic_name}</Text>}</View><Pressable onPress={()=>void removeVaccination(id,v.id).then(()=>qc.invalidateQueries({queryKey:['vaccinations',id]}))}><Text style={styles.delete}>ลบ</Text></Pressable></View>)}<View style={styles.form}><Text style={styles.cardTitle}>+ เพิ่มวัคซีน</Text><AppInput label="ชื่อวัคซีน *" value={vName} onChangeText={setVName}/><AppInput label="วันที่ฉีด YYYY-MM-DD *" value={given} onChangeText={setGiven}/><AppInput label="กำหนดครั้งถัดไป YYYY-MM-DD" value={due} onChangeText={setDue}/><AppInput label="คลินิก" value={clinic} onChangeText={setClinic}/><AppButton title="เพิ่มวัคซีน" variant="outline" onPress={()=>add.mutate()} loading={add.isPending} disabled={!vName.trim()||!given}/></View></Screen>}
const styles=StyleSheet.create({hero:{backgroundColor:colors.primaryLight,borderRadius:radius.lg,padding:spacing.md,gap:6},title:{fontSize:typography.h2,fontWeight:'900',color:colors.primaryDark},desc:{color:colors.textSecondary,lineHeight:20},section:{fontSize:typography.h2,fontWeight:'900',color:colors.text,marginTop:spacing.sm},card:{backgroundColor:colors.card,borderRadius:radius.lg,padding:spacing.md,borderWidth:1,borderColor:colors.border,flexDirection:'row',gap:10},cardTitle:{fontWeight:'900',color:colors.text,fontSize:typography.body},meta:{color:colors.textSecondary,fontSize:typography.small,marginTop:4},delete:{color:colors.emergency,fontWeight:'800'},form:{backgroundColor:colors.secondaryLight,borderRadius:radius.lg,padding:spacing.md,gap:spacing.sm}});
